#include <stdio.h>
#include <inttypes.h>
#include <string.h>
#include "pico/stdlib.h"
#include "hardware/spi.h"
#include "peripherals/tft_display/tft_display.h"
#include "lvgl/lvgl.h"
#include "drivers/ili9341/ili9341.h"
#include "hardware/timer.h"
#include "board.h"
#include "peripherals/events/events.h"
#include "peripherals/catalogue/catalogue.h"
#include "peripherals/checkout/checkout.h"

#if IDLE_SHOW_LOGO
// Generated by assets/convert_logo.py and compiled only when CMake is given
// -DIDLE_LOGO=ON, so a black-screen build carries none of the artwork.
extern "C" const lv_image_dsc_t idle_logo;
#endif

namespace {
    // LVGL render buffer
    static lv_color_t buf[DISP_HOR_RES * DISP_VER_RES / 10];

    // The critical LVGL flush callback.
    // Because this is passed to a pure C library (LVGL), it's good practice
    // to ensure it doesn't throw exceptions and maintains static linkage.
    static void my_disp_flush(lv_display_t * disp, const lv_area_t * area, uint8_t * px_map) {
        auto * color_p = reinterpret_cast<uint16_t *>(px_map);
        
        ili9341_set_window(area->x1, area->y1, area->x2, area->y2);
        
        size_t len = (area->x2 - area->x1 + 1) * (area->y2 - area->y1 + 1);
        ili9341_write_pixels(color_p, len);
        
        lv_display_flush_ready(disp);
    }
}

// --- Math Helper ---
int16_t map_coordinate(int16_t val, int16_t in_min, int16_t in_max, int16_t out_min, int16_t out_max) {
    int32_t result = (int32_t)(val - in_min) * (out_max - out_min) / (in_max - in_min) + out_min;
    
    // Clamp the output so we don't return coordinates off-screen
    if (out_min < out_max) {
        if (result < out_min) return out_min;
        if (result > out_max) return out_max;
    } else {
        if (result > out_min) return out_min;
        if (result < out_max) return out_max;
    }
    return (int16_t)result;
}

// Callback for touch screen pointing to LVGL.
// The signature is fixed by LVGL; this driver does not need the device handle,
// so it is left unnamed to say that deliberately rather than by omission.
void touchpad_read(lv_indev_t * /*indev_core*/, lv_indev_data_t * data) {
    if (xpt2046_is_pressed()) {
        data->state = LV_INDEV_STATE_PRESSED; // Updated for v9
        
        // 1. Grab raw ADC values
        uint16_t raw_x = xpt2046_spi_read(CMD_READ_X);
        uint16_t raw_y = xpt2046_spi_read(CMD_READ_Y);
        
        int16_t calc_x = raw_x;
        int16_t calc_y = raw_y;

        // 2 & 3. Handle Rotation and Mapping
        if (TOUCH_SWAP_XY) {
            calc_x = raw_y;
            calc_y = raw_x;
            
            // Because axes are swapped, map X using Y's physical boundaries
            if (TOUCH_INVERT_X) data->point.x = map_coordinate(calc_x, TOUCH_Y_MIN, TOUCH_Y_MAX, DISP_HOR_RES, 0);
            else                data->point.x = map_coordinate(calc_x, TOUCH_Y_MIN, TOUCH_Y_MAX, 0, DISP_HOR_RES);

            // And map Y using X's physical boundaries
            if (TOUCH_INVERT_Y) data->point.y = map_coordinate(calc_y, TOUCH_X_MIN, TOUCH_X_MAX, DISP_VER_RES, 0);
            else                data->point.y = map_coordinate(calc_y, TOUCH_X_MIN, TOUCH_X_MAX, 0, DISP_VER_RES);
            
        } else {
            // Normal axis mapping
            if (TOUCH_INVERT_X) data->point.x = map_coordinate(calc_x, TOUCH_X_MIN, TOUCH_X_MAX, DISP_HOR_RES, 0);
            else                data->point.x = map_coordinate(calc_x, TOUCH_X_MIN, TOUCH_X_MAX, 0, DISP_HOR_RES);

            if (TOUCH_INVERT_Y) data->point.y = map_coordinate(calc_y, TOUCH_Y_MIN, TOUCH_Y_MAX, DISP_VER_RES, 0);
            else                data->point.y = map_coordinate(calc_y, TOUCH_Y_MIN, TOUCH_Y_MAX, 0, DISP_VER_RES);
        }
        

        // DIAGNOSTIC PRINT -- Uncomment to calibrate
        if(CALIBRATE_TOUCH_MODE)
        {
            // LVGL's point coordinates are int32_t, so PRId32 rather than %d.
            printf("TOUCH PRESSED | Raw: X=%04u, Y=%04u | Mapped: X=%03" PRId32 ", Y=%03" PRId32 "\n",
                   raw_x, raw_y, data->point.x, data->point.y);
        }

    } else {
        data->state = LV_INDEV_STATE_RELEASED; // Updated for v9
    }
}

uint32_t pico_tick_get_cb(void) {
    // time_us_64() is a standard Pico SDK function. 
    // Dividing by 1000 gives us the milliseconds LVGL expects.
    return (uint32_t)(time_us_64() / 1000); 
}

// --- Touch Initialization ---
void touch_init(void) {
    // Initialize CS pin
    gpio_init(TOUCH_CS_PIN);
    gpio_set_dir(TOUCH_CS_PIN, GPIO_OUT);
    gpio_put(TOUCH_CS_PIN, 1); // Deselect by default (HIGH)

    // --- THE SPI FLUSH (Valid Command Fix) ---
    spi_set_baudrate(DISPLAY_SPI_INSTANCE, TOUCH_SPI_BAUDRATE); 
    
    gpio_put(TOUCH_CS_PIN, 0); 
    
    // Send 0xD0 (CMD_READ_X) to force a conversion and trigger power-down mode
    uint8_t dummy_tx[3] = {CMD_READ_X, 0x00, 0x00};
    uint8_t dummy_rx[3] = {0};
    
    // Read and discard to clear the Pico's internal RX FIFO
    spi_write_read_blocking(DISPLAY_SPI_INSTANCE, dummy_tx, dummy_rx, 3);
    
    gpio_put(TOUCH_CS_PIN, 1); 
    
    spi_set_baudrate(DISPLAY_SPI_INSTANCE, DISPLAY_SPI_BAUDRATE);
    // ---------------------------------------

    // Initialize IRQ pin
    gpio_init(TOUCH_IRQ_PIN);
    gpio_set_dir(TOUCH_IRQ_PIN, GPIO_IN);
    gpio_pull_up(TOUCH_IRQ_PIN); // Keep HIGH until pressed

    // 1. Create a new input device
    lv_indev_t * indev = lv_indev_create();

    // 2. Set it as a pointer (touch screen/mouse)
    lv_indev_set_type(indev, LV_INDEV_TYPE_POINTER);

    // 3. Assign your read callback function
    lv_indev_set_read_cb(indev, touchpad_read);


}

void Display::init()
{
    ili9341_init();
    lv_init();

    lv_display_t * disp = lv_display_create(DISP_HOR_RES, DISP_VER_RES);
    lv_display_set_flush_cb(disp, my_disp_flush);
    lv_display_set_buffers(disp, buf, nullptr, sizeof(buf), LV_DISPLAY_RENDER_MODE_PARTIAL);

    // Tell LVGL how to read the current time, so it knows how much has elapsed
    // between calls to lv_timer_handler() (animations, timeouts, gestures).
    //
    // This replaces the usual lv_tick_inc() call from a periodic interrupt.
    // Registering a tick callback is the better option here: LVGL pulls the
    // time whenever it needs it, so there is no 5 ms alarm interrupt running
    // forever, and no interrupt-context code in the display path at all. That
    // in turn means nothing in this module is shared between an ISR and the
    // main loop, so no `volatile` and no critical sections are needed.
    lv_tick_set_cb(pico_tick_get_cb);

    touch_init();
}

// ===========================================================================
// The screens
// ===========================================================================
//
// One LVGL screen is reused and rebuilt on every state change: lv_obj_clean()
// deletes the old widgets and each show_*() creates what it needs. Rebuilding
// rather than hiding and showing keeps each function self-contained and makes
// a stale widget left over from a previous state impossible. States change
// seconds apart at most, so the cost is irrelevant.
//
// The one exception is the cash screen, which updates on every coin. There the
// labels are kept and only their text is replaced.

namespace {

// --- Palette ---
constexpr uint32_t COLOUR_BACKGROUND = 0x0E1116;   // near-black
constexpr uint32_t COLOUR_TEXT       = 0xFFFFFF;
constexpr uint32_t COLOUR_DIM        = 0x9AA4B0;   // secondary text
constexpr uint32_t COLOUR_CASH       = 0x2E7D32;   // green
constexpr uint32_t COLOUR_ONLINE     = 0x1565C0;   // blue
constexpr uint32_t COLOUR_GOOD       = 0x43A047;
constexpr uint32_t COLOUR_FAULT      = 0xB71C1C;   // red

/// Which screen is currently built, so the cash screen can be updated in place
/// rather than rebuilt on every coin.
enum class Screen : uint8_t {
    None, Idle, Greeting, Denied, Selecting, Recount, PaymentSelect,
    Cash, OnlineWait, Qr, Thanks, Cancelled, Refund, Fault,
    UtilityMenu, SdWriting, SdResult, Taring, TareResult, Useless,
};

Screen current_screen = Screen::None;

// Widgets kept alive between calls for in-place updates. ALWAYS cleared by
// begin_screen(), because lv_obj_clean() deletes the objects they point at and
// a stale pointer here would be written through after it was freed.
lv_obj_t *cash_amount_label = nullptr;
lv_obj_t *cash_bar = nullptr;
lv_obj_t *tare_reading_label = nullptr;

void format_money(char *out, size_t length, uint32_t cents)
{
    snprintf(out, length, "$%lu.%02lu",
             (unsigned long)(cents / 100), (unsigned long)(cents % 100));
}

/// Wipe the screen and set the background. Returns the screen object.
lv_obj_t *begin_screen(Screen which, uint32_t background = COLOUR_BACKGROUND)
{
    lv_obj_t *scr = lv_screen_active();
    lv_obj_clean(scr);

    cash_amount_label = nullptr;
    cash_bar = nullptr;
    tare_reading_label = nullptr;
    current_screen = which;

    lv_obj_set_style_bg_color(scr, lv_color_hex(background), LV_PART_MAIN);
    lv_obj_set_style_bg_opa(scr, LV_OPA_COVER, LV_PART_MAIN);
    return scr;
}

lv_obj_t *make_label(lv_obj_t *parent, const char *text, const lv_font_t *font,
                     uint32_t colour, lv_align_t align, int32_t x, int32_t y)
{
    lv_obj_t *label = lv_label_create(parent);
    lv_label_set_text(label, text);
    lv_obj_set_style_text_font(label, font, LV_PART_MAIN);
    lv_obj_set_style_text_color(label, lv_color_hex(colour), LV_PART_MAIN);
    lv_obj_align(label, align, x, y);
    return label;
}

/// A touch target. The callback pushes an event and does nothing else, so the
/// state machine stays the only code that decides what a press means.
void touch_button_cb(lv_event_t *e)
{
    const events::Kind kind = static_cast<events::Kind>(
        reinterpret_cast<uintptr_t>(lv_event_get_user_data(e)));
    events::push(kind);
}

lv_obj_t *make_button(lv_obj_t *parent, const char *text, uint32_t colour,
                      events::Kind kind,
                      int32_t x, int32_t y, int32_t w, int32_t h)
{
    lv_obj_t *button = lv_button_create(parent);
    lv_obj_set_pos(button, x, y);
    lv_obj_set_size(button, w, h);
    lv_obj_set_style_bg_color(button, lv_color_hex(colour), LV_PART_MAIN);
    lv_obj_set_style_radius(button, 6, LV_PART_MAIN);

    lv_obj_add_event_cb(button, touch_button_cb, LV_EVENT_CLICKED,
                        reinterpret_cast<void *>(static_cast<uintptr_t>(kind)));

    lv_obj_t *label = lv_label_create(button);
    lv_label_set_text(label, text);
    lv_obj_set_style_text_color(label, lv_color_hex(COLOUR_TEXT), LV_PART_MAIN);
    lv_obj_set_style_text_font(label, &lv_font_montserrat_20, LV_PART_MAIN);
    lv_obj_center(label);
    return button;
}

} // namespace

void Display::run()
{
    lv_timer_handler();
}

void Display::show_idle()
{
    lv_obj_t *scr = begin_screen(Screen::Idle, 0x000000);

    // Which of these runs is decided by ONE constant, checkout::
    // IDLE_SCREEN_STYLE, so the idle screen can change without the state
    // machine knowing anything about it.
    //
    // Black is the current choice and the better one: no burn-in on a screen
    // that spends nearly all its life here, less power, and an unambiguous
    // "nothing in progress" that cannot be mistaken for a stuck transaction.
#if IDLE_SHOW_LOGO
    // Guarded by the preprocessor, not just by the constant: the image only
    // exists in the binary when CMake was told to compile it, so referring to
    // it unconditionally would not link.
    if (checkout::IDLE_SCREEN_STYLE == checkout::IdleScreen::Logo) {
        lv_obj_t *logo = lv_image_create(scr);
        lv_image_set_src(logo, &idle_logo);
        lv_obj_center(logo);
    }
#else
    (void)scr;
#endif
}

void Display::show_greeting(const char *holder_name)
{
    lv_obj_t *scr = begin_screen(Screen::Greeting);

    if (holder_name != nullptr && holder_name[0] != '\0') {
        make_label(scr, "Welcome back", &lv_font_montserrat_20, COLOUR_DIM,
                   LV_ALIGN_CENTER, 0, -50);

        // The only label on any screen whose text comes from a table a human
        // edits, so it is the only one given an explicit width. Everything else
        // here is a fixed string that was checked against the panel once; a
        // name is however long somebody types it, and without this a long one
        // would run off both edges instead of wrapping onto a second line.
        lv_obj_t *name = make_label(scr, holder_name, &lv_font_montserrat_28,
                                    COLOUR_TEXT, LV_ALIGN_CENTER, 0, -10);
        lv_obj_set_width(name, DISP_HOR_RES - 20);
        lv_obj_set_style_text_align(name, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN);
        lv_obj_align(name, LV_ALIGN_CENTER, 0, -10);
    } else {
        // A CardApproved event whose UID no longer matches a row in the
        // approved list. Greeting them anonymously is right: the tap was
        // approved when it was read, and arguing with the customer about it on
        // screen would help nobody. The mismatch is in the serial log.
        make_label(scr, "Welcome", &lv_font_montserrat_28, COLOUR_TEXT,
                   LV_ALIGN_CENTER, 0, -20);
    }

    make_label(scr, "Open the door to start", &lv_font_montserrat_20,
               COLOUR_TEXT, LV_ALIGN_CENTER, 0, 45);
}

void Display::show_access_denied()
{
    // The same red as the fault screen. They are different things, but both are
    // "stop, this did not work", and the wording is what tells them apart —
    // a customer should never have to decode a colour.
    lv_obj_t *scr = begin_screen(Screen::Denied, COLOUR_FAULT);

    make_label(scr, "ACCESS DENIED", &lv_font_montserrat_28, COLOUR_TEXT,
               LV_ALIGN_CENTER, 0, -30);
    make_label(scr, "This card is not registered", &lv_font_montserrat_20,
               COLOUR_TEXT, LV_ALIGN_CENTER, 0, 10);
    make_label(scr, "See a committee member to be added",
               &lv_font_montserrat_14, COLOUR_TEXT, LV_ALIGN_CENTER, 0, 48);

    // The UID is deliberately NOT shown. Decision D14: customers get one clear
    // message and diagnostics go to the serial log, which is where whoever
    // enrols the card needs to read it from anyway.
}

void Display::show_selecting()
{
    lv_obj_t *scr = begin_screen(Screen::Selecting);
    make_label(scr, "Welcome", &lv_font_montserrat_28, COLOUR_TEXT,
               LV_ALIGN_CENTER, 0, -40);
    make_label(scr, "Please choose a drink", &lv_font_montserrat_20, COLOUR_TEXT,
               LV_ALIGN_CENTER, 0, 5);
    make_label(scr, "Close the door when you are done", &lv_font_montserrat_14,
               COLOUR_DIM, LV_ALIGN_CENTER, 0, 45);
}

void Display::show_recount()
{
    lv_obj_t *scr = begin_screen(Screen::Recount);
    make_label(scr, "One moment...", &lv_font_montserrat_28, COLOUR_TEXT,
               LV_ALIGN_CENTER, 0, -15);
    make_label(scr, "Checking what you took", &lv_font_montserrat_14, COLOUR_DIM,
               LV_ALIGN_CENTER, 0, 25);
}

void Display::show_payment_select(const basket::Basket &basket, uint32_t owed_cents)
{
    lv_obj_t *scr = begin_screen(Screen::PaymentSelect);

    // Itemised basket, top left. Built as one multi-line string so it is a
    // single label rather than one per drink type.
    char items[128];
    size_t used = 0;
    items[0] = '\0';
    for (uint8_t i = 0; i < catalogue::CAN_COUNT; i++) {
        if (basket.taken[i] == 0) {
            continue;
        }
        const int written = snprintf(items + used, sizeof(items) - used,
                                     "%u x %s\n", basket.taken[i],
                                     catalogue::name(catalogue::from_index(i)));
        if (written < 0 || (size_t)written >= sizeof(items) - used) {
            break;      // out of room; show what fits rather than overflow
        }
        used += (size_t)written;
    }

    make_label(scr, "You took", &lv_font_montserrat_14, COLOUR_DIM,
               LV_ALIGN_TOP_LEFT, 10, 8);
    make_label(scr, items, &lv_font_montserrat_20, COLOUR_TEXT,
               LV_ALIGN_TOP_LEFT, 10, 30);

    char total[16];
    format_money(total, sizeof(total), owed_cents);
    make_label(scr, "Total", &lv_font_montserrat_14, COLOUR_DIM,
               LV_ALIGN_TOP_RIGHT, -12, 8);
    make_label(scr, total, &lv_font_montserrat_28, COLOUR_TEXT,
               LV_ALIGN_TOP_RIGHT, -12, 30);

    // The two payment choices. Coordinates match the touch-region table in
    // plan.md section 4.
    make_button(scr, "CASH", COLOUR_CASH, events::Kind::TouchCash,
                8, 150, 147, 82);
    make_button(scr, "ONLINE", COLOUR_ONLINE, events::Kind::TouchOnline,
                165, 150, 147, 82);
}

void Display::show_cash_progress(uint32_t paid_cents, uint32_t owed_cents)
{
    char paid[16];
    char owed[16];
    format_money(paid, sizeof(paid), paid_cents);
    format_money(owed, sizeof(owed), owed_cents);

    char amount[40];
    snprintf(amount, sizeof(amount), "%s of %s", paid, owed);

    // Rebuild only when arriving on this screen. Every later call is a coin
    // landing, and rebuilding then would make the display flash.
    if (current_screen != Screen::Cash) {
        lv_obj_t *scr = begin_screen(Screen::Cash);

        make_label(scr, "Insert coins", &lv_font_montserrat_20, COLOUR_DIM,
                   LV_ALIGN_TOP_MID, 0, 18);

        cash_amount_label = make_label(scr, amount, &lv_font_montserrat_28,
                                       COLOUR_TEXT, LV_ALIGN_CENTER, 0, -10);

        cash_bar = lv_bar_create(scr);
        lv_obj_set_size(cash_bar, 260, 16);
        lv_obj_align(cash_bar, LV_ALIGN_CENTER, 0, 45);
        lv_obj_set_style_bg_color(cash_bar, lv_color_hex(COLOUR_GOOD),
                                  LV_PART_INDICATOR);

        make_label(scr, "$1 and $2 coins only - no change given",
                   &lv_font_montserrat_14, COLOUR_DIM, LV_ALIGN_BOTTOM_MID, 0, -12);
    } else if (cash_amount_label != nullptr) {
        lv_label_set_text(cash_amount_label, amount);
        lv_obj_align(cash_amount_label, LV_ALIGN_CENTER, 0, -10);
    }

    if (cash_bar != nullptr) {
        const int32_t percent = (owed_cents == 0)
            ? 100
            : (int32_t)((paid_cents * 100U) / owed_cents);
        lv_bar_set_value(cash_bar, percent > 100 ? 100 : percent, LV_ANIM_OFF);
    }
}

void Display::show_online_waiting()
{
    lv_obj_t *scr = begin_screen(Screen::OnlineWait);
    make_label(scr, "Contacting", &lv_font_montserrat_20, COLOUR_TEXT,
               LV_ALIGN_CENTER, 0, -25);
    make_label(scr, "payment service...", &lv_font_montserrat_20, COLOUR_TEXT,
               LV_ALIGN_CENTER, 0, 5);
    make_label(scr, "This takes a moment", &lv_font_montserrat_14, COLOUR_DIM,
               LV_ALIGN_CENTER, 0, 45);
}

void Display::show_qr(const char *url, uint32_t owed_cents)
{
    lv_obj_t *scr = begin_screen(Screen::Qr);

    // A white plate behind the code. QR readers need a light "quiet zone"
    // around the pattern; without it a phone often will not lock on.
    lv_obj_t *plate = lv_obj_create(scr);
    lv_obj_set_size(plate, 152, 152);
    lv_obj_set_pos(plate, 12, 34);
    lv_obj_set_style_bg_color(plate, lv_color_white(), LV_PART_MAIN);
    lv_obj_set_style_border_width(plate, 0, LV_PART_MAIN);
    lv_obj_set_style_radius(plate, 4, LV_PART_MAIN);
    lv_obj_set_style_pad_all(plate, 0, LV_PART_MAIN);
    lv_obj_remove_flag(plate, LV_OBJ_FLAG_SCROLLABLE);

    lv_obj_t *qr = lv_qrcode_create(plate);
    lv_qrcode_set_size(qr, 136);
    lv_qrcode_set_dark_color(qr, lv_color_black());
    lv_qrcode_set_light_color(qr, lv_color_white());
    lv_qrcode_update(qr, url, strlen(url));
    lv_obj_center(qr);

    make_label(scr, "Scan to pay", &lv_font_montserrat_20, COLOUR_TEXT,
               LV_ALIGN_TOP_RIGHT, -14, 40);

    char total[16];
    format_money(total, sizeof(total), owed_cents);
    make_label(scr, total, &lv_font_montserrat_28, COLOUR_TEXT,
               LV_ALIGN_TOP_RIGHT, -14, 70);

    make_button(scr, "PAY CASH INSTEAD", COLOUR_CASH, events::Kind::TouchBack,
                8, 198, 304, 34);
}

void Display::show_thanks(uint32_t paid_cents, uint32_t owed_cents)
{
    lv_obj_t *scr = begin_screen(Screen::Thanks);

    char paid[16];
    format_money(paid, sizeof(paid), paid_cents);
    char line[40];
    snprintf(line, sizeof(line), "Paid %s", paid);

    // Only cash can overpay. The card path sets paid_cents = owed_cents because
    // Square confirms the exact amount, so this branch is unreachable for an
    // online sale — but it is written as a comparison rather than a check on
    // the payment method, because what makes it a tip is the arithmetic.
    //
    // The subtraction is guarded rather than assumed. These are unsigned, and
    // complete_payment() is only reached when the mass check says the money is
    // there, so paid < owed should be impossible — but "should be impossible"
    // and unsigned underflow together would put a $42 million tip on the
    // screen, which is a poor way to find out the assumption was wrong.
    const uint32_t tip_cents = paid_cents > owed_cents
                             ? paid_cents - owed_cents : 0;

    if (tip_cents == 0) {
        make_label(scr, "Thank you!", &lv_font_montserrat_28, COLOUR_GOOD,
                   LV_ALIGN_CENTER, 0, -20);
        make_label(scr, line, &lv_font_montserrat_20, COLOUR_TEXT,
                   LV_ALIGN_CENTER, 0, 20);
        return;
    }

    // Three lines, laid out like the access-denied screen. The tip amount gets
    // the large font rather than "Thank you", because the amount is the part
    // that is different from every other sale — and at 28 pt the whole sentence
    // on one line would run off a 320 px panel.
    char tip[16];
    format_money(tip, sizeof(tip), tip_cents);
    char tip_line[40];
    snprintf(tip_line, sizeof(tip_line), "%s tip!", tip);

    make_label(scr, "Thank you for the", &lv_font_montserrat_20, COLOUR_TEXT,
               LV_ALIGN_CENTER, 0, -45);
    make_label(scr, tip_line, &lv_font_montserrat_28, COLOUR_GOOD,
               LV_ALIGN_CENTER, 0, -8);
    make_label(scr, line, &lv_font_montserrat_20, COLOUR_TEXT,
               LV_ALIGN_CENTER, 0, 38);
}

void Display::show_utility_menu()
{
    lv_obj_t *scr = begin_screen(Screen::UtilityMenu);

    make_label(scr, "Maintenance", &lv_font_montserrat_28, COLOUR_TEXT,
               LV_ALIGN_TOP_MID, 0, 18);
    make_label(scr, "Insert the SD card before writing",
               &lv_font_montserrat_14, COLOUR_DIM, LV_ALIGN_TOP_MID, 0, 56);

    // Same geometry as the CASH/ONLINE pair, so the two targets a person has
    // already learned are in the same places. Colours differ, because these do
    // something to the fridge rather than complete a purchase, and a green
    // button where CASH normally sits should not mean something else entirely.
    make_button(scr, "TARE BOX", COLOUR_ONLINE, events::Kind::TouchCash,
                8, 150, 147, 82);
    make_button(scr, "WRITE SD", COLOUR_ONLINE, events::Kind::TouchOnline,
                165, 150, 147, 82);
}

void Display::show_taring()
{
    lv_obj_t *scr = begin_screen(Screen::Taring);
    make_label(scr, "Taring...", &lv_font_montserrat_28, COLOUR_TEXT,
               LV_ALIGN_CENTER, 0, -18);
    make_label(scr, "Keep the money box still", &lv_font_montserrat_14,
               COLOUR_DIM, LV_ALIGN_CENTER, 0, 24);

    // Same reason as show_sd_writing(): retare() blocks for about a second, so
    // a frame queued behind it would appear only once it had finished.
    lv_refr_now(nullptr);
}

void Display::show_tare_result(bool ok, double grams)
{
    lv_obj_t *scr = begin_screen(Screen::TareResult);

    // Three decimals, not two. The cell's noise floor is well under a tenth of
    // a gram, so this is the resolution at which "did the tare actually take"
    // is answerable; %.2f would round a drifting cell to a convincing 0.00.
    char reading[32];
    snprintf(reading, sizeof(reading), "Reading %.3f g", grams);

    make_label(scr, ok ? "Tare successful" : "Tare failed",
               &lv_font_montserrat_28, ok ? COLOUR_GOOD : COLOUR_FAULT,
               LV_ALIGN_CENTER, 0, -30);

    // Kept for in-place updates, like the cash screen's running total. The
    // number is live for as long as this screen is up, and that is the point:
    // a single frozen 0.000 g captured microseconds after the tare proves only
    // that the tare happened, whereas a number that keeps arriving and stays
    // near zero proves the cell is still sampling and has settled there.
    tare_reading_label = make_label(scr, reading, &lv_font_montserrat_20,
                                    COLOUR_TEXT, LV_ALIGN_CENTER, 0, 10);

    make_label(scr, ok ? "The box now reads empty"
                       : "No samples arrived from the cell",
               &lv_font_montserrat_14, COLOUR_DIM, LV_ALIGN_CENTER, 0, 48);
}

void Display::update_tare_reading(double grams)
{
    // Ignored unless the tare screen is the one actually on the panel. Without
    // this check a late call would write through a pointer to a label that
    // lv_obj_clean() has already freed.
    if (current_screen != Screen::TareResult || tare_reading_label == nullptr) {
        return;
    }
    char reading[32];
    snprintf(reading, sizeof(reading), "Reading %.3f g", grams);
    lv_label_set_text(tare_reading_label, reading);
}

void Display::show_sd_writing()
{
    lv_obj_t *scr = begin_screen(Screen::SdWriting);
    make_label(scr, "Writing log", &lv_font_montserrat_28, COLOUR_TEXT,
               LV_ALIGN_CENTER, 0, -30);
    make_label(scr, "to SD card", &lv_font_montserrat_28, COLOUR_TEXT,
               LV_ALIGN_CENTER, 0, 6);
    make_label(scr, "Do not remove the card", &lv_font_montserrat_14,
               COLOUR_DIM, LV_ALIGN_CENTER, 0, 48);

    // Forces the frame out to the panel NOW. Everything else on this display
    // can wait for the next superloop pass to be flushed; this cannot, because
    // the caller is about to block on the card and would otherwise leave the
    // previous screen up for the whole write.
    lv_refr_now(nullptr);
}

void Display::show_sd_result(bool ok, unsigned long lines)
{
    lv_obj_t *scr = begin_screen(Screen::SdResult);

    char detail[40];
    if (ok) {
        snprintf(detail, sizeof(detail), "%lu lines written", lines);
    } else {
        // No card, wrong format, full, or write-protected all land here. The
        // distinguishing detail is in the serial log; the panel gets one clear
        // message, the same rule the fault screen follows (decision D14).
        snprintf(detail, sizeof(detail), "Check the card and try again");
    }

    make_label(scr, ok ? "Write successful" : "Write failed",
               &lv_font_montserrat_28, ok ? COLOUR_GOOD : COLOUR_FAULT,
               LV_ALIGN_CENTER, 0, -30);
    make_label(scr, "Remove SD card", &lv_font_montserrat_20, COLOUR_TEXT,
               LV_ALIGN_CENTER, 0, 10);
    make_label(scr, detail, &lv_font_montserrat_14, COLOUR_DIM,
               LV_ALIGN_CENTER, 0, 48);
}

void Display::show_useless_button()
{
    lv_obj_t *scr = begin_screen(Screen::Useless);
    make_label(scr, "This is a useless button", &lv_font_montserrat_20,
               COLOUR_TEXT, LV_ALIGN_CENTER, 0, -10);
    make_label(scr, "Hold it for 3 seconds to write the log",
               &lv_font_montserrat_14, COLOUR_DIM, LV_ALIGN_CENTER, 0, 30);
}

void Display::show_cancelled()
{
    lv_obj_t *scr = begin_screen(Screen::Cancelled);
    make_label(scr, "Transaction cancelled", &lv_font_montserrat_20, COLOUR_TEXT,
               LV_ALIGN_CENTER, 0, -10);
    make_label(scr, "See a committee member if this is wrong",
               &lv_font_montserrat_14, COLOUR_DIM, LV_ALIGN_CENTER, 0, 30);
}

void Display::show_refund_owed(uint32_t paid_cents)
{
    lv_obj_t *scr = begin_screen(Screen::Refund);

    char amount[16];
    format_money(amount, sizeof(amount), paid_cents);

    // The amount is the biggest thing on the screen on purpose. Everything else
    // here is an apology; the number is the only part the customer needs to
    // remember when they go and find somebody.
    make_label(scr, "Drinks returned", &lv_font_montserrat_20, COLOUR_TEXT,
               LV_ALIGN_CENTER, 0, -55);
    make_label(scr, "You are owed", &lv_font_montserrat_14, COLOUR_DIM,
               LV_ALIGN_CENTER, 0, -20);
    make_label(scr, amount, &lv_font_montserrat_28, COLOUR_GOOD,
               LV_ALIGN_CENTER, 0, 12);
    make_label(scr, "The box cannot give change", &lv_font_montserrat_14,
               COLOUR_DIM, LV_ALIGN_CENTER, 0, 50);
    make_label(scr, "See a committee member", &lv_font_montserrat_14,
               COLOUR_TEXT, LV_ALIGN_CENTER, 0, 72);
}

void Display::show_fault(uint16_t code)
{
    lv_obj_t *scr = begin_screen(Screen::Fault, COLOUR_FAULT);

    char line[32];
    snprintf(line, sizeof(line), "Fault %03u", (unsigned)code);

    make_label(scr, "OUT OF SERVICE", &lv_font_montserrat_28, COLOUR_TEXT,
               LV_ALIGN_CENTER, 0, -30);
    make_label(scr, "Please see a committee member", &lv_font_montserrat_14,
               COLOUR_TEXT, LV_ALIGN_CENTER, 0, 15);
    // The code is for whoever fixes it; the detail is in the serial log.
    make_label(scr, line, &lv_font_montserrat_20, COLOUR_TEXT,
               LV_ALIGN_CENTER, 0, 50);
}
